export const SIGNUP_RESET = 'SIGNUP_RESET';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';

export const CONNECT_START = 'CONNECT_START';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_FAIL = 'CONNECT_FAIL';
export const CONNECT_HANDLER_START = 'CONNECT_HANDLER_START';
export const CONNECT_HANDLER_FAIL = 'CONNECT_HANDLER_FAIL';
export const CONNECT_DISCONNECT = 'CONNECT_DISCONNECT';